#!/usr/node/bin/node

"use strict";

var exec = require('child_process').exec;
var sprintf = require('/usr/node/node_modules/sprintf').sprintf;

function parseVmadmList(stdout, cb) {
    var vms = []
    var lines = stdout.split('\n');

    lines.forEach(function (line) {
        var fields = line.split(':');
        var uuid = fields[0];
        var alias = fields[1];
        var image_uuid = fields[2] || fields[3];
        if (uuid)
            vms[uuid] = { alias: alias, image_uuid: image_uuid };

    });

    cb(null, vms);
}

function vmadmList(cb) {
    exec('vmadm list -po uuid,alias,image_uuid,disks.0.image_uuid', function (err, stdout, stderr) {
        if (err) { throw err; }
        parseVmadmList(stdout, cb);
    });
}

function parseImgadmList(stdout, cb) {
    var lines = stdout.split('\n');
    var imgs = {};

    lines.forEach(function (line) {
        var fields = line.split(/ +/);
        var uuid = fields[0];
        var os = fields[1];
        var published = fields[2];
        var urn = fields[3];
        if (uuid.match(/^[0-9a-f-]+$/)) {
            imgs[uuid] = { os: os, published: published, urn: urn };
        }
    });

    cb(null, imgs);
}

function imgadmList(cb) {
    exec('imgadm list', function (err, stdout, stderr) {
        if (err) { throw err; }
        parseImgadmList(stdout, cb);
    });
}

var vms, imgs;

vmadmList(function (err, tvms) {
    if (err) { throw err; }
    vms = tvms;
    if (imgs)
        output(vms, imgs);
});

imgadmList(function (err, timgs) {
    if (err) { throw err; }
    imgs = timgs;
    if (vms)
        output(vms, imgs);
});

function output(vms, imgs) {
    function imageName(image_uuid) {
        if (!image_uuid || !imgs[image_uuid])
            return {urn: '-', published: '-'};
        return imgs[image_uuid];
    }

    if (process.argv.indexOf('-t') > 0) {
        for (var image_uuid in imgs) {
            var img = imgs[image_uuid];
            var c = [];
            var i;

            for (var vm_uuid in vms) {
                var vm = vms[vm_uuid];
                if (vm.image_uuid === image_uuid)
                    c.push(vm.alias + ' (' + vm_uuid + ')');
            }

            console.log(img.urn + ' (' + img.published + ')');
            if (!c.length) {
                console.log('\u2514\u2574(no image)');
            } else {
                for (i = 0; i < c.length - 1; i++)
                    console.log('\u251c\u2574' + c[i]);
                console.log('\u2514\u2574' + c[i]);
            }

            console.log()
        }

        var unknown = [];
        for (var vm_uuid in vms) {
            var vm = vms[vm_uuid];
            if (!vm.image_uuid)
                unknown.push(vm.alias + ' (' + vm_uuid + ')');
        }

        if (unknown) {
            var i;
            console.log('(no image)');
            for (i = 0; i < unknown.length - 1; i++)
                console.log('\u251c\u2574' + unknown[i]);
            console.log('\u2514\u2574' + unknown[i]);
        }
    } else {
        var format = '%-36s  %-16s  %-30s  %-10s';
        console.log(sprintf(format, 'UUID', 'ALIAS', 'IMAGE', 'PUBLISHED'));
        for (var uuid in vms) {
            var img = imageName(vms[uuid].image_uuid);
            console.log(sprintf(format, uuid, vms[uuid].alias, img.urn, img.published));
        }
    }
}

// vim: set ft=javascript:
